version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Asia/Calcutta"
    open-pull-requests-limit: 10

  # Config for GitHub Actions.
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: "Asia/Calcutta"
    open-pull-requests-limit: 10